# Alacritty Configuration File
# Theme: Gruvbox Dark Soft
# Font: JetBrains Mono Nerd Font

## Font Configuration
[font]
size = 7.0

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

## Color Scheme (Gruvbox Dark Soft)
[colors]
# Default colors
primary = { background = "#32302f", foreground = "#ebdbb2" }

# Normal colors
[colors.normal]
black = "#32302f"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

# Bright colors
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fbf1c7"

## Scrolling Configuration
[scrolling]
history = 50000

## Keyboard Bindings
[[keyboard.bindings]]
key = "PageUp"
action = "ScrollPageUp"
mode = "~AppCursor"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollPageDown"
mode = "~AppCursor"