#!/bin/bash

# Keyboard shortcuts

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor sconfiguration & Layout
$HOME/.config/bspwm/scripts/monitor_setup.sh &

# Windows configuration & Layout

bspc config border_width         2
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config active_border_color "#C3AB93"
bspc config focused_border_color "#C3AB93"
bspc config presel_feedback_color "#C3AB93"

xsetroot -cursor_name left_ptr &
xsettingsd &

bspc monitor -f $(bspc query -M | head -n1)

# external rules
bspc config external_rules_command $HOME/.config/bspwm/external-rules.sh

# rules
bspc rule -a Thunar state=floating center=on rectangle=1000x600+0+0
bspc rule -a pavucontrol state=floating center=on rectangle=1000x600+0+0
bspc rule -a Blueman-manager state=floating center=on rectangle=1000x600+0+0
bspc rule -a GParted state=floating sticky=on center=on rectangle=1000x600+0+0
bspc rule -a Alarm-clock-applet state=floating sticky=on center=on rectangle=500x500+0+0
bspc rule -a Gsimplecal state=floating center=on rectangle=500x200+0+0
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a solanum state=floating sticky=on border=off rectangle=300x200+0+0 center=on

# Disable screensaver
# xset s off
# xset -dpms
# xset s noblank

#screensaver configuration
#xautolock -time 10 -locker "~/.config/bspwm/scripts/lock.sh" -corners ---- &
xss-lock --transfer-sleep-lock -- ~/.config/bspwm/scripts/lock.sh &

# Keyboard con
xset r rate 260 55 # Set keyboard repeat rate
setxkbmap br &

# applications
picom &
numlockx &
dunst &
greenclip daemon &
alarm-clock-applet --gapplication-service &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & #Starts the Polkit authentication agent for graphical permissions
